{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red51\green51\blue51;\red247\green247\blue247;\red0\green0\blue0;
}
{\*\expandedcolortbl;;\cssrgb\c26275\c26275\c26275;\cssrgb\c97647\c97647\c97647;\cssrgb\c0\c0\c0;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs30 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 user_blocklist:\cb3 \
  \cb1 default:\cb3  \cf4 \cb1 \strokec4 1\
\
\cf2 \strokec2 case_sensitive:\cb3 \
  \cb1 default:\cb3  \cf4 \cb1 \strokec4 2\
\
\cf2 \strokec2 whole_words:\cb3 \
  \cb1 default:\cb3  \cf4 \cb1 \strokec4 3}